### ISSUE TITLE
Can not run! Can upload 'GCL.py' file?

### ISSUE THREAD

**Issue by Zhen-Peng-Wu** [wuyucheng2002/CTAug#1]
When I run the code, got a error:
ModuleNotFoundError: No module named 'GCL'.

I think you missed uploading 'GCL.py' file.

**Comment by wuyucheng2002** [comment]
Did you install PyGCL 0.1.2?
This may be because some libraries are not installed.

**Comment by Zhen-Peng-Wu** [comment]
Yes, I missed installing the PyGCL library. The code has run. Thanks.
