### ISSUE TITLE
What is the '--id_type' and '--k' for other datasets?

### ISSUE THREAD

**Issue by Zhen-Peng-Wu** [wuyucheng2002/CTAug#2]
I cannot know the '--id_type' and '--k'  for other datasets (COLLAB, RDT-B, and RDT-T datasets).
I have checked the code and the Section of 'SUBSTRUCTURE SELECTION DETAILS FOR O-GSN' in the paper.
Can you provide the '--id_type' and '--k'  for other datasets (COLLAB, RDT-B, and RDT-T datasets)?

**Comment by wuyucheng2002** [comment]
The '--id_type' and '--k' used in our experiments can be found in main.py.
<img width="785" alt="image" src="https://github.com/wuyucheng2002/CTAug/assets/88764776/10a9f38e-e20a-492e-9ece-5a12d342b3cc">
COLLAB: --id_type='complete_graph' --k=3
RDT-B: --id_type='complete_graph' --k=5
RDT-T: --id_type='complete_graph' --k=5

**Comment by Zhen-Peng-Wu** [comment]
Thank you for providing a clear answer.
It can indeed be found, but we need to watch the source code to be sure that 'k_min' is 3 and the 'k_max' is actually '-k'.
I suggest you provide a table in README.md for the parameters '--id_type' and '-k'.

**Comment by wuyucheng2002** [comment]
Ok, thank you for the suggestion, I will add this to README.md.
